export const NO_MILEAGE_SORTING = "NO_MILEAGE_SORTING";
export const ASCENDING_MILEAGE_SORTING = "ASCENDING_MILEAGE_SORTING";
export const DESCENDING_MILEAGE_SORTING = "DESCENDING_MILEAGE_SORTING";

export const API_ENDPOINT = "http://localhost:3001";
export const API_ENDPOINT_COLOR = API_ENDPOINT + "/colors";
export const API_ENDPOINT_MANUFACTURERS = API_ENDPOINT + "/manufacturers";
export const API_ENDPOINT_CAR_DETAILS = API_ENDPOINT + "/cars";
